const countryCurrencyList = [
  {
    code: "AD",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Andorra",
    phone: "376",
  },
  {
    code: "AE",
    currencyCode: "AED",
    currencyName: "UAE Dirham",
    label: "United Arab Emirates",
    phone: "971",
  },
  {
    code: "AF",
    currencyCode: "AFN",
    currencyName: "Afghani",
    label: "Afghanistan",
    phone: "93",
  },
  {
    code: "AG",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    label: "Antigua and Barbuda",
    phone: "1-268",
  },
  {
    code: "AI",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    label: "Anguilla",
    phone: "1-264",
  },
  {
    code: "AL",
    currencyCode: "ALL",
    currencyName: "Lek",
    label: "Albania",
    phone: "355",
  },
  {
    code: "AM",
    currencyCode: "AMD",
    currencyName: "Armenian Dram",
    label: "Armenia",
    phone: "374",
  },
  {
    code: "AO",
    currencyCode: "AOA",
    currencyName: "Kwanza",
    label: "Angola",
    phone: "244",
  },
  {
    code: "AQ",
    currencyCode: "USD",
    currencyName: "Dollars",
    label: "Antarctica",
    phone: "672",
  },
  {
    code: "AR",
    currencyCode: "ARS",
    currencyName: "Argentine Peso",
    label: "Argentina",
    phone: "54",
  },

  {
    code: "AT",
    currencyCode: "EUR",
    currencyName: "	Euro",
    label: "Austria",
    phone: "43",
  },
  {
    code: "AU",
    currencyCode: "AUD",
    currencyName: "	Australian Dollar",
    label: "Australia",
    phone: "61",
  },
  {
    code: "AW",
    currencyCode: "AWG",
    currencyName: "	Aruban Florin",
    label: "Aruba",
    phone: "297",
  },

  {
    code: "AZ",
    currencyCode: "AZN",
    currencyName: "	Azerbaijanian Manat",
    label: "Azerbaijan",
    phone: "994",
  },
  {
    code: "BA",
    currencyCode: "BAM",
    currencyName: "Convertible Mark",
    label: "Bosnia and Herzegovina",
    phone: "387",
  },
  {
    code: "BB",
    currencyCode: "BBD",
    currencyName: "Barbados Dollar",
    label: "Barbados",
    phone: "1-246",
  },
  {
    code: "BD",
    currencyCode: "BDT",
    currencyName: "	Taka",
    label: "Bangladesh",
    phone: "880",
  },
  {
    code: "BE",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Belgium",
    phone: "32",
  },
  {
    code: "BF",
    currencyCode: "XOF",
    currencyName: "CFA Franc BCEAO",
    label: "Burkina Faso",
    phone: "226",
  },
  {
    code: "BG",
    currencyCode: "BGN",
    currencyName: "Bulgarian Lev",
    label: "Bulgaria",
    phone: "359",
  },
  {
    code: "BH",
    currencyCode: "BHD",
    currencyName: "Bahraini Dinar",
    label: "Bahrain",
    phone: "973",
  },
  {
    code: "BI",
    currencyCode: "BIF",
    currencyName: "Burundi Franc",
    label: "Burundi",
    phone: "257",
  },
  {
    code: "BJ",
    currencyCode: "XOF",
    currencyName: "CFA Franc BCEAO",
    label: "Benin",
    phone: "229",
  },
  {
    code: "BL",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Saint Barthelemy",
    phone: "590",
  },
  {
    code: "BM",
    currencyCode: "BMD",
    currencyName: "Bermudian Dollar",
    label: "Bermuda",
    phone: "1-441",
  },
  {
    code: "BN",
    currencyCode: "BND",
    currencyName: "Brunei Dollar",
    label: "Brunei Darussalam",
    phone: "673",
  },
  {
    code: "BO",
    currencyCode: "BOB",
    currencyName: "Boliviano",
    label: "Bolivia",
    phone: "591",
  },
  {
    code: "BR",
    currencyCode: "BRL",
    currencyName: "Brazilian Real",
    label: "Brazil",
    phone: "55",
  },
  {
    code: "BS",
    currencyCode: "BSD",
    currencyName: "Bahamian Dollar",
    label: "Bahamas",
    phone: "1-242",
  },
  {
    code: "BT",
    currencyCode: "INR",
    currencyName: "Indian Rupee",
    label: "Bhutan",
    phone: "975",
  },
  {
    code: "BV",
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    label: "Bouvet Island",
    phone: "47",
  },
  {
    code: "BW",
    currencyCode: "BWP",
    currencyName: "Pula",
    label: "Botswana",
    phone: "267",
  },
  {
    code: "BY",
    currencyCode: "BYN",
    currencyName: "Belarussian Ruble",
    label: "Belarus",
    phone: "375",
  },
  {
    code: "BZ",
    currencyCode: "BZD",
    currencyName: "Belize Dollar",
    label: "Belize",
    phone: "501",
  },
  {
    code: "CA",
    currencyCode: "CAD",
    currencyName: "Canadian Dollar",
    label: "Canada",
    phone: "1",
  },
  {
    code: "CC",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    label: "Cocos (Keeling) Islands",
    phone: "61",
  },
  {
    code: "CD",
    currencyCode: "CDF",
    currencyName: "Congolese Franc",
    label: "Congo, Democratic Republic of the",
    phone: "243",
  },
  {
    code: "CF",
    currencyCode: "XAF",
    currencyName: "CFA Franc BEAC",
    label: "Central African Republic",
    phone: "236",
  },
  {
    code: "CG",
    currencyCode: "XAF",
    currencyName: "CFA Franc BEAC",
    label: "Congo, Republic of the",
    phone: "242",
  },
  {
    code: "CH",
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    label: "Switzerland",
    phone: "41",
  },
  {
    code: "CI",
    currencyCode: "XOF",
    currencyName: "CFA Franc BCEAO",
    label: "Cote d'Ivoire",
    phone: "225",
  },
  {
    code: "CK",
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    label: "Cook Islands",
    phone: "682",
  },
  {
    code: "CL",
    currencyCode: "CLP",
    currencyName: "Chilean Peso",
    label: "Chile",
    phone: "56",
  },
  {
    code: "CM",
    currencyCode: "XAF",
    currencyName: "CFA Franc BEAC",
    label: "Cameroon",
    phone: "237",
  },
  {
    code: "CN",
    currencyCode: "CNY",
    currencyName: "Yuan Renminbi",
    label: "China",
    phone: "86",
  },
  {
    code: "CO",
    currencyCode: "COP",
    currencyName: "Colombian Peso",
    label: "Colombia",
    phone: "57",
  },
  {
    code: "CR",
    currencyCode: "CRC",
    currencyName: "Costa Rican Colon",
    label: "Costa Rica",
    phone: "506",
  },
  {
    code: "CU",
    currencyCode: "CUC",
    currencyName: "Peso Convertible",
    label: "Cuba",
    phone: "53",
  },
  {
    code: "CV",
    currencyCode: "CVE",
    currencyName: "Cape Verde Escudo",
    label: "Cape Verde",
    phone: "238",
  },
  {
    code: "CW",
    currencyCode: "ANG",
    currencyName: "Netherlands Antillean Guilder",
    label: "Curacao",
    phone: "599",
  },
  {
    code: "CX",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    label: "Christmas Island",
    phone: "61",
  },
  {
    code: "CY",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Cyprus",
    phone: "357",
  },
  {
    code: "CZ",
    currencyCode: "CZK",
    currencyName: "Czech Koruna",
    label: "Czech Republic",
    phone: "420",
  },
  {
    code: "DE",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Germany",
    phone: "49",
  },
  {
    code: "DJ",
    currencyCode: "DJF",
    currencyName: "Djibouti Franc",
    label: "Djibouti",
    phone: "253",
  },
  {
    code: "DK",
    currencyCode: "DKK",
    currencyName: "Danish Krone",
    label: "Denmark",
    phone: "45",
  },
  {
    code: "DM",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    label: "Dominica",
    phone: "1-767",
  },
  {
    code: "DO",
    currencyCode: "DOP",
    currencyName: "Dominican Peso",
    label: "Dominican Republic",
    phone: "1-809",
  },
  {
    code: "DZ",
    currencyCode: "DZD",
    currencyName: "Algerian Dinar",
    label: "Algeria",
    phone: "213",
  },
  {
    code: "EC",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "Ecuador",
    phone: "593",
  },
  {
    code: "EE",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Estonia",
    phone: "372",
  },
  {
    code: "EG",
    currencyCode: "EGP",
    currencyName: "Egyptian Pound",
    label: "Egypt",
    phone: "20",
  },
  {
    code: "EH",
    currencyCode: "MAD",
    currencyName: "Moroccan Dirham",
    label: "Western Sahara",
    phone: "212",
  },
  {
    code: "ER",
    currencyCode: "ERN",
    currencyName: "Nakfa",
    label: "Eritrea",
    phone: "291",
  },
  {
    code: "ES",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Spain",
    phone: "34",
  },
  {
    code: "ET",
    currencyCode: "ETB",
    currencyName: "Ethiopian Birr",
    label: "Ethiopia",
    phone: "251",
  },
  {
    code: "FI",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Finland",
    phone: "358",
  },
  {
    code: "FJ",
    currencyCode: "FJD",
    currencyName: "Fiji Dollar",
    label: "Fiji",
    phone: "679",
  },
  {
    code: "FK",
    currencyCode: "FKP",
    currencyName: "Falkland Islands Pound",
    label: "Falkland Islands (Malvinas)",
    phone: "500",
  },
  {
    code: "FM",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "Micronesia, Federated States of",
    phone: "691",
  },
  {
    code: "FO",
    currencyCode: "DKK",
    currencyName: "Danish Krone",
    label: "Faroe Islands",
    phone: "298",
  },
  {
    code: "FR",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "France",
    phone: "33",
    suggested: true,
  },
  {
    code: "GA",
    currencyCode: "XAF",
    currencyName: "CFA Franc BEAC",
    label: "Gabon",
    phone: "241",
  },
  {
    code: "GB",
    currencyCode: "GBP",
    currencyName: "Pound Sterling",
    label: "United Kingdom",
    phone: "44",
  },
  {
    code: "GD",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    label: "Grenada",
    phone: "1-473",
  },
  {
    code: "GE",
    currencyCode: "GEL",
    currencyName: "Lari",
    label: "Georgia",
    phone: "995",
  },
  {
    code: "GF",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "French Guiana",
    phone: "594",
  },
  {
    code: "GG",
    currencyCode: "GBP",
    currencyName: "Pound Sterling",
    label: "Guernsey",
    phone: "44",
  },
  {
    code: "GH",
    currencyCode: "GHS",
    currencyName: "Ghana Cedi",
    label: "Ghana",
    phone: "233",
  },
  {
    code: "GI",
    currencyCode: "GIP",
    currencyName: "Gibraltar Pound",
    label: "Gibraltar",
    phone: "350",
  },
  {
    code: "GL",
    currencyCode: "DKK",
    currencyName: "Danish Krone",
    label: "Greenland",
    phone: "299",
  },
  {
    code: "GM",
    currencyCode: "GMD",
    currencyName: "Dalasi",
    label: "Gambia",
    phone: "220",
  },
  {
    code: "GN",
    currencyCode: "GNF",
    currencyName: "Guinea Franc",
    label: "Guinea",
    phone: "224",
  },
  {
    code: "GP",
    currencyCode: "EUR	",
    currencyName: "Euro",
    label: "Guadeloupe",
    phone: "590",
  },
  {
    code: "GQ",
    currencyCode: "XAF",
    currencyName: "CFA Franc BEAC",
    label: "Equatorial Guinea",
    phone: "240",
  },
  {
    code: "GR",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Greece",
    phone: "30",
  },
  {
    code: "GS",
    currencyCode: "USD",
    currencyName: "US Dollars",
    label: "South Georgia and the South Sandwich Islands",
    phone: "500",
  },
  {
    code: "GT",
    currencyCode: "GTQ",
    currencyName: "Quetzal",
    label: "Guatemala",
    phone: "502",
  },
  {
    code: "GU",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "Guam",
    phone: "1-671",
  },
  {
    code: "GW",
    currencyCode: "XOF",
    currencyName: "CFA Franc BCEAO",
    label: "Guinea-Bissau",
    phone: "245",
  },
  {
    code: "GY",
    currencyCode: "GYD",
    currencyName: "Guyana Dollar",
    label: "Guyana",
    phone: "592",
  },
  {
    code: "HK",
    currencyCode: "HKD",
    currencyName: "Hong Kong Dollar",
    label: "Hong Kong",
    phone: "852",
  },
  {
    code: "HM",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    label: "Heard Island and McDonald Islands",
    phone: "672",
  },
  {
    code: "HN",
    currencyCode: "HNL",
    currencyName: "Lempira",
    label: "Honduras",
    phone: "504",
  },
  {
    code: "HR",
    currencyCode: "HRK",
    currencyName: "Kuna",
    label: "Croatia",
    phone: "385",
  },
  {
    code: "HT",
    currencyCode: "HTG",
    currencyName: "Gourde",
    label: "Haiti",
    phone: "509",
  },
  {
    code: "HU",
    currencyCode: "HUF",
    currencyName: "Forint",
    label: "Hungary",
    phone: "36",
  },
  {
    code: "ID",
    currencyCode: "IDR",
    currencyName: "Rupiah",
    label: "Indonesia",
    phone: "62",
  },
  {
    code: "IE",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Ireland",
    phone: "353",
  },
  {
    code: "IL",
    currencyCode: "ILS",
    currencyName: "New Israeli Sheqel",
    label: "Israel",
    phone: "972",
  },
  {
    code: "IM",
    currencyCode: "GBP",
    currencyName: "Pound Sterling",
    label: "Isle of Man",
    phone: "44",
  },
  {
    code: "IN",
    currencyCode: "INR",
    currencyName: "Indian Rupee",
    label: "India",
    phone: "91",
  },
  {
    code: "IO",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "British Indian Ocean Territory",
    phone: "246",
  },
  {
    code: "IQ",
    currencyCode: "IQD",
    currencyName: "Iraqi Dinar",
    label: "Iraq",
    phone: "964",
  },
  {
    code: "IR",
    currencyCode: "IRR",
    currencyName: "Iranian Rial",
    label: "Iran, Islamic Republic of",
    phone: "98",
  },
  {
    code: "IS",
    currencyCode: "ISK",
    currencyName: "Iceland Krona",
    label: "Iceland",
    phone: "354",
  },
  {
    code: "IT",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Italy",
    phone: "39",
  },
  {
    code: "JE",
    currencyCode: "GBP",
    currencyName: "Pound Sterling",
    label: "Jersey",
    phone: "44",
  },
  {
    code: "JM",
    currencyCode: "JMD",
    currencyName: "Jamaican Dollar",
    label: "Jamaica",
    phone: "1-876",
  },
  {
    code: "JO",
    currencyCode: "JOD",
    currencyName: "Jordanian Dinar",
    label: "Jordan",
    phone: "962",
  },
  {
    code: "JP",
    currencyCode: "JPY",
    currencyName: "Yen",
    label: "Japan",
    phone: "81",
  },
  {
    code: "KE",
    currencyCode: "KES",
    currencyName: "Kenyan Shilling",
    label: "Kenya",
    phone: "254",
  },
  {
    code: "KG",
    currencyCode: "KGS",
    currencyName: "Som",
    label: "Kyrgyzstan",
    phone: "996",
  },
  {
    code: "KH",
    currencyCode: "KHR",
    currencyName: "Riel",
    label: "Cambodia",
    phone: "855",
  },
  {
    code: "KI",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    label: "Kiribati",
    phone: "686",
  },
  {
    code: "KM",
    currencyCode: "KMF",
    currencyName: "Comoro Franc",
    label: "Comoros",
    phone: "269",
  },
  {
    code: "KN",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    label: "Saint Kitts and Nevis",
    phone: "1-869",
  },
  {
    code: "KP",
    currencyCode: "KPW",
    currencyName: "North Korean Won",
    label: "Korea, Democratic People's Republic of",
    phone: "850",
  },
  {
    code: "KR",
    currencyCode: "KRW",
    currencyName: "Won",
    label: "Korea, Republic of",
    phone: "82",
  },
  {
    code: "KW",
    currencyCode: "KWD",
    currencyName: "Kuwaiti Dinar",
    label: "Kuwait",
    phone: "965",
  },
  {
    code: "KY",
    currencyCode: "KYD",
    currencyName: "Cayman Islands Dollar",
    label: "Cayman Islands",
    phone: "1-345",
  },
  {
    code: "KZ",
    currencyCode: "KZT",
    currencyName: "Tenge",
    label: "Kazakhstan",
    phone: "7",
  },
  {
    code: "LA",
    currencyCode: "LAK",
    currencyName: "Kip",
    label: "Lao People's Democratic Republic",
    phone: "856",
  },
  {
    code: "LB",
    currencyCode: "LBP",
    currencyName: "Lebanese Pound",
    label: "Lebanon",
    phone: "961",
  },
  {
    code: "LC",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    label: "Saint Lucia",
    phone: "1-758",
  },
  {
    code: "LI",
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    label: "Liechtenstein",
    phone: "423",
  },
  {
    code: "LK",
    currencyCode: "LKR",
    currencyName: "Sri Lanka Rupee",
    label: "Sri Lanka",
    phone: "94",
  },
  {
    code: "LR",
    currencyCode: "LRD",
    currencyName: "Liberian Dollar",
    label: "Liberia",
    phone: "231",
  },
  {
    code: "LS",
    currencyCode: "LSL",
    currencyName: "Loti",
    label: "Lesotho",
    phone: "266",
  },
  {
    code: "LT",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Lithuania",
    phone: "370",
  },
  {
    code: "LU",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Luxembourg",
    phone: "352",
  },
  {
    code: "LV",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Latvia",
    phone: "371",
  },
  {
    code: "LY",
    currencyCode: "LYD",
    currencyName: "Libyan Dinar",
    label: "Libya",
    phone: "218",
  },
  {
    code: "MA",
    currencyCode: "MAD",
    currencyName: "Moroccan Dirham",
    label: "Morocco",
    phone: "212",
  },
  {
    code: "MC",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Monaco",
    phone: "377",
  },
  {
    code: "MD",
    currencyCode: "MDL",
    currencyName: "Moldovan Leu",
    label: "Moldova, Republic of",
    phone: "373",
  },
  {
    code: "ME",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Montenegro",
    phone: "382",
  },
  {
    code: "MF",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Saint Martin (French part)",
    phone: "590",
  },
  {
    code: "MG",
    currencyCode: "MGA",
    currencyName: "Malagasy Ariary",
    label: "Madagascar",
    phone: "261",
  },
  {
    code: "MH",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "Marshall Islands",
    phone: "692",
  },
  {
    code: "MK",
    currencyCode: "MKD",
    currencyName: "Denar",
    label: "Macedonia, the Former Yugoslav Republic of",
    phone: "389",
  },
  {
    code: "ML",
    currencyCode: "XOF",
    currencyName: "CFA Franc BCEAO",
    label: "Mali",
    phone: "223",
  },
  {
    code: "MM",
    currencyCode: "MMK",
    currencyName: "Kyat",
    label: "Myanmar",
    phone: "95",
  },
  {
    code: "MN",
    currencyCode: "MNT",
    currencyName: "Tugrik",
    label: "Mongolia",
    phone: "976",
  },
  {
    code: "MO",
    currencyCode: "MOP",
    currencyName: "Pataca",
    label: "Macao",
    phone: "853",
  },
  {
    code: "MP",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "Northern Mariana Islands",
    phone: "1-670",
  },
  {
    code: "MQ",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Martinique",
    phone: "596",
  },
  {
    code: "MR",
    currencyCode: "MRU",
    currencyName: "Ouguiya",
    label: "Mauritania",
    phone: "222",
  },
  {
    code: "MS",
    currencyCode: "XCD",
    currencyName: "Euro",
    label: "East Caribbean Dollar",
    phone: "1-664",
  },
  {
    code: "MT",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Malta",
    phone: "356",
  },
  {
    code: "MU",
    currencyCode: "MUR",
    currencyName: "Mauritius Rupee",
    label: "Mauritius",
    phone: "230",
  },
  {
    code: "MV",
    currencyCode: "MVR",
    currencyName: "Rufiyaa",
    label: "Maldives",
    phone: "960",
  },
  {
    code: "MW",
    currencyCode: "MWK",
    currencyName: "Kwacha",
    label: "Malawi",
    phone: "265",
  },
  {
    code: "MX",
    currencyCode: "MXV",
    currencyName: "Mexican Unidad de Inversion (UDI)",
    label: "Mexico",
    phone: "52",
  },
  {
    code: "MY",
    currencyCode: "MYR",
    currencyName: "Malaysian Ringgit",
    label: "Malaysia",
    phone: "60",
  },
  {
    code: "MZ",
    currencyCode: "MZN",
    currencyName: "Mozambique Metical",
    label: "Mozambique",
    phone: "258",
  },
  {
    code: "NA",
    currencyCode: "NAD",
    currencyName: "Namibia Dollar",
    label: "Namibia",
    phone: "264",
  },
  {
    code: "NC",
    currencyCode: "XPF",
    currencyName: "CFP Franc",
    label: "New Caledonia",
    phone: "687",
  },
  {
    code: "NE",
    currencyCode: "XOF",
    currencyName: "CFA Franc BCEAO",
    label: "Niger",
    phone: "227",
  },
  {
    code: "NF",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    label: "Norfolk Island",
    phone: "672",
  },
  {
    code: "NG",
    currencyCode: "NGN",
    currencyName: "Naira",
    label: "Nigeria",
    phone: "234",
  },
  {
    code: "NI",
    currencyCode: "NIO",
    currencyName: "Cordoba Oro",
    label: "Nicaragua",
    phone: "505",
  },
  {
    code: "NL",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Netherlands",
    phone: "31",
  },
  {
    code: "NO",
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    label: "Norway",
    phone: "47",
  },
  {
    code: "NP",
    currencyCode: "NPR",
    currencyName: "Nepalese Rupee",
    label: "Nepal",
    phone: "977",
  },
  {
    code: "NR",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    label: "Nauru",
    phone: "674",
  },
  {
    code: "NU",
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    label: "Niue",
    phone: "683",
  },
  {
    code: "NZ",
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    label: "New Zealand",
    phone: "64",
  },
  {
    code: "OM",
    currencyCode: "OMR",
    currencyName: "Rial Omani",
    label: "Oman",
    phone: "968",
  },
  {
    code: "PA",
    currencyCode: "PAB",
    currencyName: "Balboa",
    label: "Panama",
    phone: "507",
  },
  {
    code: "PE",
    currencyCode: "PEN",
    currencyName: "Nuevo Sol",
    label: "Peru",
    phone: "51",
  },
  {
    code: "PF",
    currencyCode: "XPF",
    currencyName: "CFP Franc",
    label: "French Polynesia",
    phone: "689",
  },
  {
    code: "PG",
    currencyCode: "PGK",
    currencyName: "Kina",
    label: "Papua New Guinea",
    phone: "675",
  },
  {
    code: "PH",
    currencyCode: "PHP",
    currencyName: "Philippine Peso",
    label: "Philippines",
    phone: "63",
  },
  {
    code: "PK",
    currencyCode: "PKR",
    currencyName: "Pakistan Rupee",
    label: "Pakistan",
    phone: "92",
  },
  {
    code: "PL",
    currencyCode: "PLN",
    currencyName: "Zloty",
    label: "Poland",
    phone: "48",
  },
  {
    code: "PM",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Saint Pierre and Miquelon",
    phone: "508",
  },
  {
    code: "PN",
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    label: "Pitcairn",
    phone: "870",
  },
  {
    code: "PR",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "Puerto Rico",
    phone: "1",
  },
  {
    code: "PS",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "Palestine, State of",
    phone: "970",
  },
  {
    code: "PT",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Portugal",
    phone: "351",
  },
  {
    code: "PW",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "Palau",
    phone: "680",
  },
  {
    code: "PY",
    currencyCode: "PYG",
    currencyName: "Guarani",
    label: "Paraguay",
    phone: "595",
  },
  {
    code: "QA",
    currencyCode: "QAR",
    currencyName: "Qatari Rial",
    label: "Qatar",
    phone: "974",
  },
  {
    code: "RE",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Reunion",
    phone: "262",
  },
  {
    code: "RO",
    currencyCode: "RON",
    currencyName: "Romanian Leu",
    label: "Romania",
    phone: "40",
  },
  {
    code: "RS",
    currencyCode: "RSD",
    currencyName: "Serbian Dinar",
    label: "Serbia",
    phone: "381",
  },
  {
    code: "RU",
    currencyCode: "RUB",
    currencyName: "Russian Ruble",
    label: "Russian Federation",
    phone: "7",
  },
  {
    code: "RW",
    currencyCode: "RWF",
    currencyName: "Rwanda Franc",
    label: "Rwanda",
    phone: "250",
  },
  {
    code: "SA",
    currencyCode: "SAR",
    currencyName: "Saudi Riyal",
    label: "Saudi Arabia",
    phone: "966",
  },
  {
    code: "SB",
    currencyCode: "SBD",
    currencyName: "Solomon Islands Dollar",
    label: "Solomon Islands",
    phone: "677",
  },
  {
    code: "SC",
    currencyCode: "SCR",
    currencyName: "Seychelles Rupee",
    label: "Seychelles",
    phone: "248",
  },
  {
    code: "SD",
    currencyCode: "SDG",
    currencyName: "Sudanese Pound",
    label: "Sudan",
    phone: "249",
  },
  {
    code: "SE",
    currencyCode: "SEK",
    currencyName: "Swedish Krona",
    label: "Sweden",
    phone: "46",
  },
  {
    code: "SG",
    currencyCode: "SGD",
    currencyName: "Singapore Dollar",
    label: "Singapore",
    phone: "65",
  },
  {
    code: "SH",
    currencyCode: "SHP",
    currencyName: "Saint Helena Pound",
    label: "Saint Helena",
    phone: "290",
  },
  {
    code: "SI",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Slovenia",
    phone: "386",
  },
  {
    code: "SJ",
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    label: "Svalbard and Jan Mayen",
    phone: "47",
  },
  {
    code: "SK",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Slovakia",
    phone: "421",
  },
  {
    code: "SL",
    currencyCode: "SLE",
    currencyName: "Leone",
    label: "Sierra Leone",
    phone: "232",
  },
  {
    code: "SM",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "San Marino",
    phone: "378",
  },
  {
    code: "SN",
    currencyCode: "XOF",
    currencyName: "CFA Franc BCEAO",
    label: "Senegal",
    phone: "221",
  },
  {
    code: "SO",
    currencyCode: "SOS",
    currencyName: "Somali Shilling",
    label: "Somalia",
    phone: "252",
  },
  {
    code: "SR",
    currencyCode: "SRD",
    currencyName: "Surinam Dollar",
    label: "Suriname",
    phone: "597",
  },
  {
    code: "SS",
    currencyCode: "SSP",
    currencyName: "South Sudanese Pound",
    label: "South Sudan",
    phone: "211",
  },
  {
    code: "ST",
    currencyCode: "STN",
    currencyName: "Dobra",
    label: "Sao Tome and Principe",
    phone: "239",
  },
  {
    code: "SV",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "El Salvador",
    phone: "503",
  },
  {
    code: "SX",
    currencyCode: "ANG",
    currencyName: "Netherlands Antillean Guilder",
    label: "Sint Maarten (Dutch part)",
    phone: "1-721",
  },
  {
    code: "SY",
    currencyCode: "SYP",
    currencyName: "Syrian Pound",
    label: "Syrian Arab Republic",
    phone: "963",
  },
  {
    code: "SZ",
    currencyCode: "SZL",
    currencyName: "Lilangeni",
    label: "Swaziland",
    phone: "268",
  },
  {
    code: "TC",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "Turks and Caicos Islands",
    phone: "1-649",
  },
  {
    code: "TD",
    currencyCode: "XAF",
    currencyName: "CFA Franc BEAC",
    label: "Chad",
    phone: "235",
  },
  {
    code: "TF",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "French Southern Territories",
    phone: "262",
  },
  {
    code: "TG",
    currencyCode: "XOF",
    currencyName: "CFA Franc BCEAO",
    label: "Togo",
    phone: "228",
  },
  {
    code: "TH",
    currencyCode: "THB",
    currencyName: "Baht",
    label: "Thailand",
    phone: "66",
  },
  {
    code: "TJ",
    currencyCode: "TJS",
    currencyName: "Somoni",
    label: "Tajikistan",
    phone: "992",
  },
  {
    code: "TK",
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    label: "Tokelau",
    phone: "690",
  },
  {
    code: "TL",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "Timor-Leste",
    phone: "670",
  },
  {
    code: "TM",
    currencyCode: "TMT",
    currencyName: "Turkmenistan New Manat",
    label: "Turkmenistan",
    phone: "993",
  },
  {
    code: "TN",
    currencyCode: "TND",
    currencyName: "Tunisian Dinar",
    label: "Tunisia",
    phone: "216",
  },
  {
    code: "TO",
    currencyCode: "TOP",
    currencyName: "Paanga",
    label: "Tonga",
    phone: "676",
  },
  {
    code: "TR",
    currencyCode: "TRY",
    currencyName: "Turkish Lira",
    label: "Turkey",
    phone: "90",
  },
  {
    code: "TT",
    currencyCode: "TTD",
    currencyName: "Trinidad and Tobago Dollar",
    label: "Trinidad and Tobago",
    phone: "1-868",
  },
  {
    code: "TV",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    label: "Tuvalu",
    phone: "688",
  },
  {
    code: "TW",
    currencyCode: "TWD",
    currencyName: "New Taiwan Dollar",
    label: "Taiwan, Province of China",
    phone: "886",
  },
  {
    code: "TZ",
    currencyCode: "TZS",
    currencyName: "Tanzanian Shilling",
    label: "United Republic of Tanzania",
    phone: "255",
  },
  {
    code: "UA",
    currencyCode: "UAH",
    currencyName: "Hryvnia",
    label: "Ukraine",
    phone: "380",
  },
  {
    code: "UG",
    currencyCode: "UGX",
    currencyName: "Uganda Shilling",
    label: "Uganda",
    phone: "256",
  },
  {
    code: "US",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "United States",
    phone: "1",
  },
  {
    code: "UY",
    currencyCode: "UYU",
    currencyName: "Peso Uruguayo",
    label: "Uruguay",
    phone: "598",
  },
  {
    code: "UZ",
    currencyCode: "UZS",
    currencyName: "Uzbekistan Sum",
    label: "Uzbekistan",
    phone: "998",
  },
  {
    code: "VA",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Holy See (Vatican City State)",
    phone: "379",
  },
  {
    code: "VC",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    label: "Saint Vincent and the Grenadines",
    phone: "1-784",
  },
  {
    code: "VE",
    currencyCode: "VED",
    currencyName: "Bolivar",
    label: "Venezuela",
    phone: "58",
  },
  {
    code: "VG",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "British Virgin Islands",
    phone: "1-284",
  },
  {
    code: "VI",
    currencyCode: "USD",
    currencyName: "US Dollar",
    label: "US Virgin Islands",
    phone: "1-340",
  },
  {
    code: "VN",
    currencyCode: "VND",
    currencyName: "Dong",
    label: "Vietnam",
    phone: "84",
  },
  {
    code: "VU",
    currencyCode: "VUV",
    currencyName: "Vatu",
    label: "Vanuatu",
    phone: "678",
  },
  {
    code: "WF",
    currencyCode: "XPF",
    currencyName: "CFP Franc",
    label: "Wallis and Futuna",
    phone: "681",
  },
  {
    code: "WS",
    currencyCode: "WST",
    currencyName: "Tala",
    label: "Samoa",
    phone: "685",
  },
  {
    code: "XK",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Kosovo",
    phone: "383",
  },
  {
    code: "YE",
    currencyCode: "YER",
    currencyName: "Yemeni Rial",
    label: "Yemen",
    phone: "967",
  },
  {
    code: "YT",
    currencyCode: "EUR",
    currencyName: "Euro",
    label: "Mayotte",
    phone: "262",
  },
  {
    code: "ZA",
    currencyCode: "ZAR",
    currencyName: "Rand",
    label: "South Africa",
    phone: "27",
  },
  {
    code: "ZM",
    currencyCode: "ZMW",
    currencyName: "Zambian Kwacha",
    label: "Zambia",
    phone: "260",
  },
  {
    code: "ZW",
    currencyCode: "ZWL",
    currencyName: "Zimbabwe Dollar",
    label: "Zimbabwe",
    phone: "263",
  },
];

export default countryCurrencyList;
