const farmAnimalsList = [
  { name: "Alpaca" },
  { name: "Beefalo" },
  { name: "Black Rock chicken" },
  { name: "Botswana" },
  { name: "Buffalo" },
  { name: "Banteng" },
  { name: "Cow" },
  { name: "Cat" },
  { name: "Chicken" },
  { name: "Common Carp" },
  { name: "Camel" },
  { name: "Donkey" },
  { name: "Dog" },
  { name: "Duck" },
  { name: "Emu" },
  { name: "Goat" },
  { name: "Gayal" },
  { name: "Guinea pig" },
  { name: "Goose" },
  { name: "Horse" },
  { name: "Honey Bee" },
  { name: "Llama" },
  { name: "Mule" },
  { name: "Pig" },
  { name: "Pigeon" },
  { name: "Reindeer" },
  { name: "Rhea" },
  { name: "Rabbit" },
  { name: "Sheep" },
  { name: "Silkworm" },
  { name: "Snail" },
  { name: "Turkey" },
  { name: "Yak" },
  { name: "Yakalo" },
  { name: "Yakow" },
  { name: "Zebu" },
  { name: "Żubroń" },
];

export default farmAnimalsList;
